### ISSUE TITLE
use builder in Event

### ISSUE THREAD

**Issue by davidmoten** [pwittchen/ReactiveBus#7]
A suggestion. Your `Event` class has lots of `create` overloads which are easy to mix up (what if your `data` is a `String` (which is also a `Serializable`)). Use a builder instead for safer and more readable code. See https://github.com/davidmoten/java-builder-pattern-tricks.

**Comment by pwittchen** [comment]
Thanks for the suggestion. I heard that it's good practice to create Builder when there are more than 3 parameters in the constructor or factory method. Here I have max 3 parameters. Nevertheless, it may be confusing due to `Serializable` type as you mentioned, so it's good idea.

**Comment by pwittchen** [comment]
Done in PR #8.
